apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: df8ltujoq-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:a95bc9a1adfbd3794b74e1e31196a875fd018d12@sha256:6f7803241818bb6ee70911b03f32114b7981eabcbd5feec1d0d534bc4d0cf8c5
          name: container-image
